# Generated by Django 5.2.17 on 2026-09-25 10:09

import bookings.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.core.validators
from django.conf import settings
from django.db import migrations, models


def refuse_if_overlaps_exist(apps, schema_editor):
    """The exclusion constraint below can't be added while overlapping
    non-cancelled bookings already exist. Postgres would fail with a
    cryptic 'could not create exclusion constraint' - list the actual
    clashes instead so they can be fixed (cancel one of each pair) and the
    migration re-run. Seeded data never overlaps, so normally this is a
    no-op."""
    Booking = apps.get_model("bookings", "Booking")
    active = Booking.objects.exclude(status="cancelled")
    clashes = []
    for b in active.order_by("property_id", "check_in"):
        others = active.filter(
            property_id=b.property_id,
            check_in__lt=b.check_out,
            check_out__gt=b.check_in,
            pk__gt=b.pk,
        )
        for o in others:
            clashes.append(
                f"  property {b.property_id}: booking {b.pk} "
                f"({b.check_in}->{b.check_out}) overlaps booking {o.pk} "
                f"({o.check_in}->{o.check_out})"
            )
    if clashes:
        raise RuntimeError(
            "Can't add the no-overlap constraint - these non-cancelled "
            "bookings overlap. Cancel one of each pair (e.g. in Django Admin) "
            "or re-seed, then migrate again:\n" + "\n".join(clashes)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0002_propertyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Needed so a GiST index can combine `property_id WITH =` (a plain
        # integer) with the date-range overlap. Trusted extension on PG13+,
        # so the DB owner can create it without superuser.
        BtreeGistExtension(),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, help_text="Number of people staying. Must not exceed the property's capacity (checked on booking).", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('guests__gte', 1)), name='booking_guests_at_least_one'),
        ),
        migrations.RunPython(refuse_if_overlaps_exist, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[('property', '='), (bookings.models.DateRange('check_in', 'check_out'), '&&')], name='booking_no_overlap_per_property'),
        ),
    ]
