# Generated by Django 5.2.17 on 2026-09-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_booking_guests_no_overlap"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_received", "Booking received (guest)"),
                            ("booking_confirmed", "Booking confirmed (guest)"),
                            ("booking_cancelled", "Booking cancelled (guest)"),
                            ("admin_new_booking", "New booking alert (admin)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recipients", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to send"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (booking changed)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sending_started_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status"], name="bookingemail_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "kind"), name="one_email_per_booking_kind"
                    )
                ],
            },
        ),
    ]
