# Generated by Django 5.2.17 on 2026-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingemail",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("guest", "Cancelled by the guest"),
                    ("host", "Cancelled by the host"),
                    ("payment_expired", "Payment time ran out"),
                    ("payment_failed", "Payment failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
