# Generated by Django 5.2.17 on 2026-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingemail",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("gmail", "Gmail API"),
                    ("brevo", "Brevo (Gmail fallback)"),
                    ("smtp", "SMTP"),
                    ("console", "Console (printed to the log)"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
