# Generated by Django 5.2.17 on 2026-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden by an admin: not shown publicly and not counted in the rating. The guest still can't post another one.",
            ),
        ),
    ]
