# Generated by Django 5.2.17 on 2026-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_attempt",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Part of the Stripe idempotency key. Only goes up if an attempt never produced a session and its stored expiry got too close for Stripe to accept again.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.TextField(
                blank=True,
                help_text="Stripe-hosted payment page; valid until expires_at, so 'Pay now' can reuse it.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                help_text="Empty until the guest reaches checkout (unique once set).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
