# Generated by Django 5.2.17 on 2026-09-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_checkout_session_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Awaiting payment"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=12,
            ),
        ),
    ]
