# Generated by Django 5.2.17 on 2026-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_cancelled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_attempt",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Part of the refund's idempotency key booking-<id>-refund-<n>. Only goes up after Stripe itself reports a refund as failed - a retry after a network error reuses the same key, so it can never refund twice.",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_failure_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "No refund"),
                    ("pending", "Refund pending"),
                    ("refunded", "Refunded"),
                    ("failed", "Refund failed"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_refund_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
