# Generated by Django 5.2.17 on 2026-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short, guest-facing name for the listing, e.g. "Cozy studio near the seafront".', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer free-text description shown on the property detail page.')),
                ('location', models.CharField(help_text='Free-text location, e.g. "Thessaloniki, Greece". Used for search/filtering.', max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Nightly price. Decimal (not float) so money never loses precision.', max_digits=8)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests the property sleeps.')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity labels, e.g. ["wifi", "parking", "pool"].')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive properties are hidden from customer-facing listings but kept for history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
