# Generated by Django 5.2.17 on 2026-09-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Photo URL. Demo data uses stock photo URLs (see the Faker seed script); real uploads are a later, nice-to-have ticket.', max_length=500)),
                ('is_cover', models.BooleanField(default=False, help_text="Marks this as the property's thumbnail/cover photo. At most one per property.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
            options={
                'ordering': ['-is_cover', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property',), name='unique_cover_image_per_property')],
            },
        ),
    ]
