# Generated by Django 5.2.17 on 2026-09-28 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Exact map position (admins only; guests see a ~500 m area). Set together with longitude.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Exact map position. Set together with latitude.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="property_lat_lng_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="property_latitude_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="property_longitude_in_range",
            ),
        ),
    ]
