# Generated by Django 5.2.17 on 2026-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_backfill_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(help_text='Photo URL: a photo uploaded to the S3 bucket (TICKET-036, uploads/s3.py) or any pasted https image URL. Demo data uses stock photo URLs (see the Faker seed script).', max_length=500),
        ),
    ]
