# Generated by Django 5.2.17 on 2026-09-30 06:46

import bookings.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_propertyimage_upload_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist is already created by bookings.0002; IF NOT EXISTS keeps
        # this migration independent of that order. Never dropped on the way
        # back (the bookings constraint still needs it) - hence the no-op.
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gist", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name="BlockedPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(help_text="First closed night.")),
                (
                    "end",
                    models.DateField(
                        help_text="The day after the last closed night (exclusive, like a booking's check-out)."
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Why the dates are closed (admins only - guests never see it).",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_periods",
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "closed period",
                "ordering": ["start", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gt", models.F("start"))),
                        name="blockedperiod_end_after_start",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("property", "="),
                            (bookings.models.DateRange("start", "end"), "&&"),
                        ],
                        name="blockedperiod_no_overlap_per_property",
                    ),
                ],
            },
        ),
    ]
